# 公共配置
spring:
  application:
    name: oidc-idp

server:
  port: 9300
  servlet:
    # 使用应用名称，防止 cookie 冲突
    context-path: /${spring.application.name}

peacetrue:
  idp-oidc:
    idp:
      protocol:
      host:
    sp:
      protocol: ${peacetrue.idp-oidc.idp.protocol}
      host: ${peacetrue.idp-oidc.idp.host}
    #      port:
    sps:
      - protocol: ${peacetrue.idp-oidc.sp.protocol}
        host: ${peacetrue.idp-oidc.sp.host}
        port:
      - protocol: ${peacetrue.idp-oidc.sp.protocol}
        host: ${peacetrue.idp-oidc.sp.host}
        port:

# 默认使用内存模式
spring.profiles.group.default: devx,memory
# 开发环境使用 H2 数据库
spring.profiles.group.dev: devx,h2
# 生产环境使用 MySQL 数据库
spring.profiles.group.prod: mysql

spring.profiles.group.h2: db
spring.profiles.group.mysql: db

---
# 开发环境
spring.config.activate.on-profile: devx

spring:
  thymeleaf:
    cache: false
  security:
    #配置初始化用户
    user:
      name: admin
      password: 123456
      roles: USER

# 认证客户端 host
peacetrue:
  idp-oidc:
    idp:
      protocol: http
      host: 127.0.0.1
      port: ${server.port}
    sps:
      - protocol: ${peacetrue.idp-oidc.sp.protocol}
        host: ${peacetrue.idp-oidc.sp.host}
        port: 9301
      - protocol: ${peacetrue.idp-oidc.sp.protocol}
        host: ${peacetrue.idp-oidc.sp.host}
        port: 9302

logging:
  level:
    root: info
    org.springframework: info
    org.springframework.security: trace
    com.github.peacetrue: trace

---
# 生产环境
spring.config.activate.on-profile: prod

spring:
  thymeleaf:
    cache: true

peacetrue:
  idp-oidc:
    idp:
      protocol: https
      host: peacetrue.cn
      port: 443
    sps:
      - protocol: ${peacetrue.idp-oidc.sp.protocol}
        host: ${peacetrue.idp-oidc.sp.host}
        port: 443
      - protocol: ${peacetrue.idp-oidc.sp.protocol}
        host: ${peacetrue.idp-oidc.sp.host}
        port: 443

logging:
  level:
    root: info
    com.github.peacetrue: trace
  file:
    name: ${spring.application.name}.log
#
#server:
#  tomcat:
#    basedir: tomcat
#    accesslog:
#      enabled: true

---
# 内存配置
spring.config.activate.on-profile: memory
spring:
  flyway:
    enabled: false

---
# H2 数据库配置
spring.config.activate.on-profile: h2

# 访问地址（无需认证）：http://127.0.0.1:9300/oidc-idp/h2-console
# JDBC URL：jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true
#        web-admin-password: 1qw2!QW@

---
# MySQL数据库配置
spring.config.activate.on-profile: mysql

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sso_oidc
    username: root
    password: 1qw2!QW@
