# 预定义变量（不设值）
#客户端对应的序号，客户端1序号为 1、客户端2序号为 2
serial-number:
#本服务主机信息
sp:
  protocol:
  host:
  port:
#idp服务主机信息
idp:
  protocol:
  host:
  port:

---
#公共配置
#idp 和 sp 默认在同一台机器上
idp:
  protocol: ${sp.protocol}
  host: ${sp.host}

spring:
  application:
    name: oidc-sp-${serial-number}
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        #认证服务端
        provider:
          oidc-idp:
            issuer-uri: ${idp.protocol}://${idp.host}:${idp.port}/oidc-idp
        #认证客户端
        registration:
          oidc-sp:
            provider: oidc-idp
            client-id: oidc-sp-${serial-number}
            client-name: oidc-sp-${serial-number}
            client-secret: secret${serial-number}
            authorization-grant-type: authorization_code
            redirect-uri: "${sp.protocol}://${sp.host}:${sp.port}${server.servlet.context-path}/login/oauth2/code/{registrationId}"
            scope: openid


server:
  port: 930${serial-number}
  servlet:
    # 使用应用名称，防止 cookie 冲突
    context-path: /${spring.application.name}

---
#客户端 1
spring.config.activate.on-profile: default,client1

serial-number: 1

---
#客户端 2
spring.config.activate.on-profile: client2

serial-number: 2

---
#开发环境
spring.config.activate.on-profile: default,dev

logging:
  level:
    root: info
    com.github.peacetrue: trace
    org.springframework: debug
    org.springframework.security: trace

# 不要使用 localhost，OAuth2 规范要求
sp:
  protocol: http
  host: 127.0.0.1
  port: ${server.port}

idp:
  port: 9300

---
#生产环境
spring.config.activate.on-profile: prod

sp:
  protocol: https
  host: peacetrue.cn
  port: 443

idp:
  port: ${sp.port}

logging:
  level:
    root: info
    com.github.peacetrue: trace
  file:
    name: ${spring.application.name}.log

#server:
#  tomcat:
#    basedir: tomcat
#    accesslog:
#      enabled: true