= 会话情况

用户从 SP 登录后，IDP 会有一个会话，SP 会有一个会话，SP 还具有一个访问令牌，那么这三者之间有什么关联呢？本文会结合 https://github.com/spring-projects-experimental/spring-authorization-server[spring-authorization-server^] 中样章的运行效果进行讨论。

随着授权码认证流程的展开，会浮现出如下几个疑问：

. SP 如何判断当前用户的状态
. SP 如何更新会话时长
. IDP 如何判断当前用户状态
. IDP 如何更新会话时长

== SP 如何判断当前用户的状态

SP 如何判断当前用户的状态呢？有三种可能性：

. 根据会话有效时长
. 根据访问令牌有效时长
. 根据以上两者

情形一：仅根据会话有效时长而不考虑访问令牌，则 SP 具有一个独立的会话，访问令牌对其不产生影响，可能会导致一个问题，在使用访问令牌调用资源服务的接口，因为访问令牌已经失效而调用失败。

情形二：仅根据访问令牌有效时长而不考虑会话，则每次请求都需要手动传递访问令牌以表明身份，服务端需要维护所有访问令牌并检查当前请求的访问令牌是否失效。

情形三：先根据会话再根据会话中存储的访问令牌，这样整体表现出的有效时长为两者中的较小值。

=== 设计测试案例

==== 会话未过期但访问令牌已过期，此时系统作何反应？

.初始化系统配置
* IDP 会话 30 分钟
* SP 会话 30 分钟
* 访问令牌有效期 3 秒

SP 登录后，过 5 秒访问资源服务，查看系统响应情况：

系统检测到访问令牌已过期，使用刷新令牌重新获取访问令牌。具体实现代码：

. OAuth2AuthorizedClientArgumentResolver
. DefaultOAuth2AuthorizedClientManager
. RefreshTokenOAuth2AuthorizedClientProvider

刷新令牌也设置为 3 秒，重复上述操作：


=== 前后端不分离

身份认证通过后，在会话中保存身份信息，每次请求时判断会话中是否包含身份信息。会话存在一个有效时长，访问令牌也存在一个有效时长；如果会话有效时长大于访问令牌有效时长，则可能出现访问令牌已经过期，会话尚未过期，仍然可以访问系统的情况；如果会话有效时长小于访问令牌有效时长，则可能出现访问令牌尚未过期，会话已经过期，无法访问系统的情况。如此一来只能让会话有效时长等于访问令牌有效时长。

=== 前后端分离
